name: conan-package

on:
  push:
    paths:
      - 'src/**'
      - 'test_package/**'
      - 'include/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/requirements*'
      - '.gitattributes'
    branches:
        - main
        - 'CURA-*'
        - 'PP-*'
        - '[0-9].[0-9]*'
        - '[0-9].[0-9][0-9]*'

jobs:
# FIXME: Use main once merged
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@CURA-11622_conan_v2
    with:
      project_name: arcus
    secrets: inherit
