---
name: conan-export
on:
  push:
    paths:
      - 'python/**'
      - 'src/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/export-package.yml'
    branches:
      - main
      - master
      - 'CURA-*'
      - 'release/**'
  pull_request:
    branches:
      - main
      - master
      - dev
      - 'release/**'
env:
  CONAN_USER: ${{ secrets.CONAN_USER }}
  CONAN_PASS: ${{ secrets.CONAN_PASS }}
jobs:
  get-semver:
    runs-on: ubuntu-20.04
    outputs:
      semver_full: ${{ steps.gittool.outputs.fullSemVer }}
      channel: ${{ steps.get-channel.outputs.channel }}
    steps:
    - name: Checkout Arcus
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - id: gittool
      name: GitTools
      uses: gittools/actions/gitversion/execute@v0.9.13
    - id: get-channel
      name: Get Conan channel
      run: |
        if [ "${{ github.ref_type }}" = "master" ]; then
          echo '::set-output name=channel::stable'
        elif [ "${{ github.ref_type }}" = "main" ]; then
          echo '::set-output name=channel::stable'
        else
          echo '::set-output name=channel::testing'
        fi
  conan-package:
    runs-on: ${{ matrix.os }}
    needs: get-semver
    strategy:
      matrix:
        os: [ macos-10.15, windows-2022, ubuntu-20.04 ]
    steps:
    - name: Checkout Arcus
      uses: actions/checkout@v3
    - name: Setup Python and pip
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.4'
        architecture: 'x64'
        cache: 'pip'
    - name: Prepare Conan and sip-build
      run: |
        pip install --require-hashes -r requirements.txt
        conan config install https://github.com/Ultimaker/conan-config.git -a "-b CURA-9177_Fix_CI_CD" -tf ~/.conan
        conan profile new default --detect
        conan user -p $CONAN_PASS -r ultimaker $CONAN_USER
    - name: Cache Conan local repository packages
      uses: actions/cache@v3.0.2
      with:
        path: |
          ~/.conan/data
        key: ${{ runner.os }}-conan
    - name: Create the Packages and Upload
      run: |
        conan create . arcus/${{ needs.get-semver.outputs.semver_full }}@${{ github.repository_owner }}/${{ needs.get-semver.outputs.channel }} -pr:b cura_build.jinja --build=missing
        conan upload "*" -r ultimaker --all -c
